### ISSUE TITLE
`Borders::...signal` methods should take `impl Signal<Item = Option<Border>>`

### ISSUE THREAD

**Issue by databasedav** [MoonZoon/MoonZoon#140]
this is more ergonomic than, say, zeroing out the width to produce no border

**Comment by MartinKavik** [comment]
I would rather change it to `impl Signal<Item = impl Into<Option<Border>>>` to make it backward-compatible and more ergonomic. (You probably had it on your mind already).

Feel free to create a PR.

_Note:_ I haven't need to use the version with `Option` yet because changing border width often causes annoying layout changes because the width change affects the element size - see https://github.com/MoonZoon/MoonZoon/issues/99 for more info.
