### ISSUE TITLE
Chat example locks up on 3 clients

### ISSUE THREAD

**Issue by Geordi7** [MoonZoon/MoonZoon#165]
1. I run the chat server
2. I opened two incognito chrome windows and sent a message from each client and they are propagated correctly.
3. I opened a third incognito chrome window, it seems to load correctly and the session is identified in the server log
4. I "send a message" in each of the three windows, none of the requests show up in the server log (and neither do they appear in the clients
5. I close the third client window and all the requests OF THE OTHER CLIENTS show up in the server log, and they are then propagated correctly

**Comment by Geordi7** [comment]
I tried to reproduce this again and now it's working :/

**Comment by MartinKavik** [comment]
Probably caused by  the browser's SSE connection limit being too low (6 connections) per domain when connecting through HTTP. This happened to me several times during an app development. The problem doesn't exist in practice with HTTPS and you can enable it even for development in your `MoonZoon.toml`.

More info here: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
