### ISSUE TITLE
Is this the replacement for seed?

### ISSUE THREAD

**Issue by alecnotthompson** [MoonZoon/MoonZoon#29]
Heyo! I'm starting a rust+wasm project and am picking my ui library. As of about 6 months ago when I last explored seed was my favorite but now I see the main maintainer is working more on this. What's the reason for two?

**Comment by MartinKavik** [comment]
Seed is a "classic" frontend framework - it helps you to manage HTML, CSS and browser APIs in a reasonable way. It follows the Elm architecture and it isn't opinionated about the backend and build tools (e.g. Trunk or webpack). I'm not the original Seed author and I don't own the Seed crate.

MoonZoon has different philosophy - it has own "ecosystem" to make sure everything works as expected and API is as simple as possible. It doesn't follow any dogmatic rules (e.g. the Elm architecture or "everything is a component") and it's faster than Seed / React and other frameworks. Also it has a nice Rust API instead of many macros / templates to hide ugly CSS, HTML, JS API and their behavior. The most significant differences are the backend part (Moon), mzoon (MoonZoon CLI) and MoonZoon Cloud. 
However own ecosystem doesn't mean you can't use your favorite tools when you want - for instance I'm just writing an example with Solana to demonstrate how to connect to a blockchain.
Another reason is money - Seed development isn't sustainable for me because it's super hard to find sponsors. MoonZoon Cloud or similar services have much bigger potential to pay for the development / my rent. Or when I decide to start a new project / business, I don't have to kill time with research and connecting different parts of the future app - I'll just pick MoonZoon + Heroku or MZ Cloud and write at least a MVP very quickly.

**Comment by alecnotthompson** [comment]
Thanks for the informative response! Money is the reason I'm looking around as well. I like the batteries included approach but want to make sure I'm not restricted. Would you say zoon is worth using even if its just managing UI? How tied is it to rendering html in the end? When do you think you'll be ready to put it on crates.io?

**Comment by MartinKavik** [comment]
> Would you say zoon is worth using even if its just managing UI?

`@avi` on Discord has written a chat app with Zoon and his custom backend APIs. It's deployed on Render.com. I've deployed a Zoon app to Netflify. 
There is a missing MZ CLI command(s) to make the process of deploying / developing with a standalone Zoon simpler, but it's possible. The Moon renders the initial `index.html` and works as a dev/prod server and it should help with SEO in the future, but you can replace it with something else.

> When do you think you'll be ready to put it on crates.io?

My plan:
1. Finish the example with Solana.
2. Finish the `time_tracker` example. It's the only example with virtual actors.
3. Implement CLI command `mzoon new`.
4. Release all crates on crates.io.
5. Start to work on MoonZoon Cloud.
6. Write a book about MZ (?)

I'm not brave enough to guess any dates, but it should give you an idea what are next steps.

**Comment by NeverGivinUp** [comment]
> My plan:
>     1. Finish the example with Solana.
>     2. Finish the `time_tracker` example. It's the only example with virtual actors.
>     3. Implement CLI command `mzoon new`.
>     4. Release all crates on crates.io.
>     5. Start to work on MoonZoon Cloud.
>     6. Write a book about MZ (?)

I'm fairly certain this is included in Point 4, but such a huge and important task I'd like to bring it to attention:
_Document all `struct`s and `enum`s._

The Rust community seems to have an exceptionally high percentage of very experienced programmers, experienced in many different libraries and frameworks. I guess they can just guess, where you're coming from with many concepts.

Less experienced people must rely on being taught by documentation -- e.g. compiler errors, the standard library's or nalgebra carefully made and maintained API documentation.

Lacking or low quality documentation means lack of productivity for many potential users. Some will work through it. Most will look for other options.

**Comment by MartinKavik** [comment]
> I'm fairly certain this is included in Point 4, but such a huge and important task I'd like to bring it to attention:
Document all structs and enums.

Perhaps it will be included in the point 6 to attract more people to the MoonZoon Cloud. Documentation is the most time consuming part of the project and I don't have motivation from a business point of view to focus on it in the near future. Also docs in README + examples + blogs + Discord should be enough for most people.

Btw maybe the project https://github.com/OpenHope/OpenHope could be interesting for you if you wonder why I talk about a "business point of view" and don't want to attract less experienced people now to this open source project.

**Comment by MartinKavik** [comment]
UPDATE: I'm still improving MoonZoon and plan to continue because I'm happy with its architecture, performance and API. Documentation and full backend implementation is still missing but we are getting there slowly and the frontend side should be already more powerful than Seed's one - closing the issue.

P.S. 
- Currently working on a MoonZoon component library based on [Preline](https://preline.co/) so it'll be much easier to write your new web quickly and integrate your Figma/Penpot(?) designs.
- Tauri integration to make MoonZoon working in desktop/mobile apps is on the roadmap.
