### ISSUE TITLE
`RoundedCorners` being lost when passing iterator of `RawElement`'s to `Paragraph.contents`

### ISSUE THREAD

**Issue by databasedav** [MoonZoon/MoonZoon#43]
i was able to reproduce this behavior by replacing [this](https://github.com/MoonZoon/MoonZoon/blob/main/examples/chat/frontend/src/app/view.rs#L67) line in the chat example with `markup::Object::Text(text) => El::new().s(Borders::all(Border::new().color(RED_5).width(2))).s(RoundedCorners::all(20)).child(Text::new(text)).into_raw_element(),`

this happens on both firefox and chrome on Ubuntu 20.10

**Comment by MartinKavik** [comment]
The problem was this line: https://github.com/MoonZoon/MoonZoon/blob/0a2d2f2d415b2421ff058152599e6c3833b2ac2b/crates/zoon/src/element/paragraph.rs#L20

I've recently added the line to resolve problems with floating in paragraphs. `Align` left/right in `Paragraph` is implemented as `float: left/right`. But `float`  works only with `inline`.  However you've discovered one of multiple problems with `inline` that I wasn't aware of:
- We can't set `width` / `height` of `inline` elements.
- `inline` elements don't support `Transform`.
- We can't observe `inline` elements size.
- `RoundedCorners` code is based on `ResizeObserver` so it wasn't able to set the radius correctly because of the previous point and the result was the default value `0`.

I hope the default Zoon element `display` value `inline-flex` would be enough for most cases where a `Paragraph` is used. It means I've removed the mentioned line in my working branch and I'll push it with other changes later.

When problems with `Paragraph` layout appear we'll have to find ideally an alternative to `inline` or add something like `.inline()` to elements or add a new element `InlineEl::new()` or automatically wrap a `Paragraph` child to an `inline` element, etc. We'll see. 
Until it's merged you can just add one nested `El` in the `Paragraph` content as a workaround.

P.S. I've linked the issue from the modified code, please don't close the issue yet. We'll wait for more realworld use-cases with `Paragraph` and alignment to resolve it properly.

**Comment by MartinKavik** [comment]
I've just merged https://github.com/MoonZoon/MoonZoon/pull/52 with a new example `paragraph`. The example demonstrates where is the `Paragraph` element useful and how to use it. `Paragraph` still sets `display: inline` to all its direct children so some limitations mentioned above still apply but it shouldn't be a problem in practice. 

Also there is the element `Row` with its method `.multiline` for cases where we want wrapped rows of elements.

Finally, the commit https://github.com/MoonZoon/MoonZoon/commit/9e20ba1450156924e7bb92baf13cb4cc6adf78ad allows to use at least fixed rounded corners (i.e. your `RoundedCorners` has to be defined in pixels - without `.*_max` method calls). Therefore I'm closing the issue as resolved.
