### ISSUE TITLE
Zoon color picker

### ISSUE THREAD

**Issue by databasedav** [MoonZoon/MoonZoon#48]
this should include a customizable `Element` that shows the color and the various sliders (something like https://www.hsluv.org/) and also utilities for converting to and from various color formats

**Comment by MartinKavik** [comment]
Perhaps we can write an example inspired by an extended hsluv picker (as you suggested):
![image](https://user-images.githubusercontent.com/18517402/148135258-44e615d4-c0e0-4dc5-8e43-303995e13d4d.png)
and then write an example with a custom Dropdown menu.

Then anybody can look at the code and write similar elements or create a component library. I'm not sure we can write color/date picker customizable/universal enough for integration directly among the basic Zoon elements.

**Comment by databasedav** [comment]
fyi for now u can use `TextInput::new().update_raw_el(|raw_el| raw_el .attr("type", "color"))`, the text mutable stores a hex of the current color that u can set/react to, this also has the advantage of hooking into the OS's native color picker, although an in browser reactive element like the above would be ideal

**Comment by MartinKavik** [comment]
Update:
- I'm working on a component library for MoonZoon based on Preline and they also use a native color picker you described in the previous comment.
- MoonZoon now supports all color formats/spaces that are supported by the browser so you can pass even hex strings directly to MoonZoon element styles. It means the integration of existing JS color pickers or that native one should be easier.
- Color pickers are often very color space or app specific, see for example https://oklch.com. I'm not sure how the ideal basic extendable color picker should look like or work - it needs a deeper research.
- Converting between colors is often simple but may be very complex, see for example https://docs.rs/palette/latest/palette/convert/index.html and https://docs.rs/lightningcss/1.0.0-alpha.54/lightningcss/values/color/enum.CssColor.html.

So I think the next step would be probably to add new `InputType` variant `Color` to `TextInput` element with related HTML attributes together with a new MZ example if needed. This way we can support the native color picker without the workaround `update_raw_el`. I don't plan to do research for a custom MZ color picker in the foreseeable future because I don't have realworld examples and capacity for it. That's why I'm closing the issue for now, I'll reopen it when needed.

If you want, you can create a new MZ issue named like *"Add `InputType::Color`"*  with more context so I have some foundations for designing the API.
