### ISSUE TITLE
Zoon without HTML abstraction?

### ISSUE THREAD

**Issue by flosse** [MoonZoon/MoonZoon#59]
When porting an existing app without changing the backend/CSS/etc., I'd love to have a way to describe the HTML structure and event handlers without an abstraction.
I know that's not the focus of MoonZoon but I'm just curious if there could be a "raw" layer where I could use a syntax like Seed or [maud](https://maud.lambda.xyz/)?

**Comment by MartinKavik** [comment]
@flosse See https://github.com/MoonZoon/MoonZoon/pull/60 - do you think the API would be enough to make the migration easier for you? Would you change the API somehow?

**Comment by flosse** [comment]
Thanks for the quick reply!
#60 is indeed an attempt to find some solutions.
Still, I miss the possibility to mix HTML with values and events.

I've never written macros before, but probably this is a good opportunity to learn it now ;-)

Without knowing if it's even possible, I could imagine a seed-like syntax like this one

```rust
div![
    button!["-", ev!(|_: events:Click|decrement())],
    p![counter().signal()]
    button!["+", ev!(|_: events:Click|increment())],
]
```
or maud like

```rust
html! {
    div {
        button { "-" ev(|_: events:Click|decrement()) }
        p { counter().signal() }
        button { "-" ev(|_: events:Click|increment()) }
    }
}
```

or even without macros 

```rust
el("div")
  .child(el("button").txt("-").event_handler(|_: events:Click|decrement()))
  .child(el("p").signal(counter().signal())
  .child(el("button").txt("-").event_handler(|_: events:Click|increment()));
```

Do you have any idea if it's worth learning how to write macros to implement something like this?

**Comment by MartinKavik** [comment]
> Do you have any idea if it's worth learning how to write macros to implement something like this?

Well, learning to write macros is always worth it, but prepare for real fighting while you'll be writing template macros:

---

```rust
div![
    button!["-", ev!(|_: events:Click|decrement())],
    p![counter().signal()]
    button!["+", ev!(|_: events:Click|increment())],
]
```
1. You don't need to learn to write proc macros, `macro_rules!` should be enough.
2. There are some `macro_rules!` in `zoon/lib.rs` like [element_vec](https://github.com/MoonZoon/MoonZoon/blob/e7466bb00e34a88ceea2f3cc81662ac193ffdc61/crates/zoon/src/lib.rs#L183-L198) for inspiration.
3. You should be able to transform macros like `div!` directly to Zoon items like `RawHtmlEl`.
4. I had to write some [extra traits in Seed](https://github.com/seed-rs/seed/blob/cce9685c05b07043ae42d39bcb9023f74a954ae0/src/virtual_dom/update_el.rs) to satisfy Rust compiler and allow to pass, for instance, both `impl Iterator` and `Option`/`Vec` to element macros. Perhaps nightly Rust with `specialization`/`min_specialization` features would help here when you encounter similar obstacles. 
5. Perhaps you'll need to use some "hacks" / helpers in `macro_rules!` definitions. Examples:
    1. Create unique identifiers with the `gensym` crate ([example in Zoon](https://github.com/MoonZoon/MoonZoon/blob/e7466bb00e34a88ceea2f3cc81662ac193ffdc61/crates/zoon/src/lib.rs#L173))
    2. Create identifiers from parts with the `paste` crate ([example in Zoon](https://github.com/MoonZoon/MoonZoon/blob/e7466bb00e34a88ceea2f3cc81662ac193ffdc61/crates/zoon/src/lib.rs#L176-L179))
    3. Create `macro_rules` with `macro_rules` ([a helper in Seed](https://github.com/seed-rs/seed/blob/cce9685c05b07043ae42d39bcb9023f74a954ae0/src/shortcuts.rs#L9-L45))
   
---

```rust
html! {
    div {
        button { "-" ev(|_: events:Click|decrement()) }
        p { counter().signal() }
        button { "-" ev(|_: events:Click|increment()) }
    }
}
```
1. Most Rust template engines don't support rendering to an object tree (aka vdom) if I'm not wrong. I've seen rendering to vdom only in the `typed-html` crate - see the [last section](https://github.com/bodil/typed-html#render-to-a-virtual-dom) in its Readme. Zoon doesn't have VDOM so you just need to map the template to Zoon `RawHtmlEl` but it looks like the "mapping process" would be different for each existing template engine (I'm not sure how to do that correctly/at all in Maud).
2. You can write your template engine. You'd need to write proc macros. There are multiple crates in the MoonZoon repo with proc macros (difficulty: from [moon_entry_macros](https://github.com/MoonZoon/MoonZoon/blob/e7466bb00e34a88ceea2f3cc81662ac193ffdc61/crates/moon_entry_macros/src/lib.rs) to [route_macro](https://github.com/MoonZoon/MoonZoon/blob/main/crates/route_macro/src/lib.rs)). You basically need to write a parser, a standard proc macro way is to use crates `syn`, `proc_macro2` and other ones like the Maud's parser does ([parse.rs](https://github.com/lambda-fairy/maud/blob/main/maud_macros/src/parse.rs)) or maybe you can use a parser library like [Pest](https://pest.rs/) (there is a chat Zoon example with a simple Pest parser to parse [messages with emoticons](https://github.com/MoonZoon/MoonZoon/blob/e7466bb00e34a88ceea2f3cc81662ac193ffdc61/examples/chat/frontend/src/markup.rs)).
3. There is an [issue](https://github.com/Pauan/rust-dominator/issues/33) in the Dominator repo related to JSX/templates/HTML macros.
4. And what about Dominator API? (The [counter example](https://github.com/Pauan/rust-dominator/blob/1f541fd7170287e657c4cae1ff418430cfd625ed/examples/counter/src/lib.rs).)

---

```rust
el("div")
  .child(el("button").txt("-").event_handler(|_: events:Click|decrement()))
  .child(el("p").signal(counter().signal())
  .child(el("button").txt("-").event_handler(|_: events:Click|increment()));
```
It looks pretty similar to the current Zoon API. It's also similar to Dominator API. It would be the simplest API to implement - it should be just a slim wrapper for `RawHtmlEl` + `RawSvgEl`.

---

So I think I'll merge the linked PR because it allows to use Markdown and similar things with Zoon. And you can experiment with templates if you want. I don't want to include a template engine directly to Zoon but feel free to update the `markup` example in this repo - ideally the section with the Maud example - with your template system/API and your crate in Cargo.toml dependencies.

**Comment by flosse** [comment]
Thank you so much for that extensive feedback, it's a great starting point for me.
I'll let you know as soon as I build something usable.
As far as I am concerned, we can close this issue with that.

**Comment by flosse** [comment]
FYI:
I played around with different approaches in order to create a nice syntax but finally I ended up by just creating an alias for `RawHtmlEl` and `RawSvglEl`

```rust
fn html(tag_name: &str) -> RawHtmlEl {
    RawHtmlEl::new(tag_name)
} 
fn svg(tag_name: &str) -> RawSvgEl {
    RawSvgEl::new(tag_name)
}
```

This way it is at least somewhat readable:

```rust
fn navbar() -> impl Element {
    html("nav")
        .class("navbar")
        .child(
            html("div").class("navbar-brand").child(
                html("a")
                    .class("navbar-item")
                    .child(html("b").child("Brand Name")),
            ),
        )
        .child(
            html("div").class("navbar-menu").child(
                html("div").class("navbar-start").child(
                    html("div").class("navbar-item").child(
                        html("div")
                            .class("field")
                            .class("is-grouped")
                            .child(
                                html("p").class("control").child(
                                    html("a")
                                        .class("button")
                                        .child("foo")
                                        .event_handler(|_: events::Click| {
                                            foo()
                                        }),
                                ),
                            )
                            .child(
                                html("p").class("control").child(
                                    html("a")
                                        .class("button")
                                        .child("bar")
                                        .event_handler(|_: events::Click| {
                                            bar()
                                        }),
                                ),
                            )
                            .child(
                                html("p").class("control").child(
                                    html("a")
                                        .class("button")
                                        .child("baz")
                                        .event_handler(|_: events::Click| {
                                            bar()
                                        }),
                                ),
                            )
                    ),
                ),
            ),
        )
}
```

So a possible strategy to port existing frontends would be

1. Use [`RawHtmlEl::from_markup`](https://github.com/MoonZoon/MoonZoon/blob/c9b2e2cb514d3362c64809aa33113a07c74a84ed/crates/zoon/src/element/raw_el.rs#L225) like you proposed in #60.
2. Replace the dynamic parts with manually created elements as shown above.
3. Replace interesting parts with custom implemented components, like you did with e.g. [`Button`](https://github.com/MoonZoon/MoonZoon/blob/c9b2e2cb514d3362c64809aa33113a07c74a84ed/crates/zoon/src/element/button.rs#L11).
