### ISSUE TITLE
add convenience method for maximum `LayerIndex`

### ISSUE THREAD

**Issue by databasedav** [MoonZoon/MoonZoon#78]
this would just make it more idiomatic (zoonic?) to bring elements to the front with a signal

**Comment by MartinKavik** [comment]
hey, I've just merged the PR: https://github.com/MoonZoon/MoonZoon/pull/80
Changes:
- Added `const`s `LayerIndex::MIN_VALUE/MAX_VALUE`.
- `LayerIndex::new/with_signal` accept `i32` instead of `u32`.
- Added the "pulsing rectangle" CSS animation to the `layers` example. (It'll be replaced with native Zoon animation API.)
- The example `layers` refactored - the rectangle ordering is managed with the help of `MutableVec` instead of `LayerIndex`.

I've rewritten the `layers` example to a "more zoonic (?)" solution. I think it's better to just move the element "physically" in the DOM to change its layer/z-index instead of just pretending it has moved by setting its CSS `z-index`. `z-index` could be really painful to work with and Zoon/Dominator/MutableVec is smart enough to not call the element render function on the element move so it should be also quite cheap operation in practice.
However, there is a temporary problem - CSS animations are reset by the browser during the element move so we still have to use CSS `z-index` / `LayerIndex` for elements with such animations. It will be resolved by native Zoon animation API and once the API is stable enough I'll probably mark the `LayerIndex` and `Transitions` as deprecated. 

I'm closing the issue since it should be resolved by the mentioned PR but feel free to add your ideas/comments to the issue or to MZ Discord.
