### ISSUE TITLE
MoonZoon should be color-neutral

### ISSUE THREAD

**Issue by NeverGivinUp** [MoonZoon/MoonZoon#98]
Currently MoonZoon has two built in color concepts: the `HSLuv` color space and a [palette](https://github.com/MoonZoon/MoonZoon/blob/main/crates/zoon/src/style/named_color.rs). Integrating them is convenient, as framework users do not need to think about colors much. They can just use them. 

For anything but technology demonstrations, application developers will want to use a palette that matches their corporate identity and expresses their visual design goals, though. A predefined palette is just dead weight to them. Luckily it can just be ignored, by not importing the `named_color` module.

A built in color space and color space library is  more problematic. Just like built in colors, it biases framework users toward using it. However it also is part of function signatures. So framework users that prefer a different color space need to actively work around it.

I think I remember reading somewhere that @MartinKavik was very pleased to have found `HSLuv`, because it seemed like a panacea to all color-related problems. However it is not and there can not be one. You have to make a trade off between [a number of design goals](https://bottosson.github.io/posts/colorpicker/#what-makes-a-good-color-picker%3F).

Personally, I will be using the OKLab color space -- see the [comparison to HSLuv](https://bottosson.github.io/posts/colorpicker/#hsluv) -- which has also been integrated into the Unity game engine and seems to be finding its way into the next [CSS Color](https://www.w3.org/TR/css-color-4/#ok-lab) specification. I with be using it via the [palette crate](https://crates.io/crates/palette), which does not have a stable API yet, and a number of open issues, but seems focused, well designed and very actively developed.

So my preference would be for MoonZoon to be color-neutral and make it easy for users to use their color space and color library of choice.

**Comment by MartinKavik** [comment]
I see OKLab for the first time - probably because it wasn't existing while I was starting with the MZ development.
_oklch_ really looks like a better _hsluv_ (based on my quick research and your suggestions of course).
Other related links:
- [palette](https://docs.rs/palette/0.6.0/palette/index.html)::[Oklcha](https://docs.rs/palette/0.6.0/palette/type.Oklcha.html#)
- https://forum.figma.com/t/support-oklab-and-oklch/18287 + https://www.figma.com/community/plugin/889859275438287504/HCL-Color
- https://oklch.evilmartians.io/

MoonZoon's philosophy is to provide the best default options but also allow you to integrate your favorite tools whenever possible.
So I don't want to remove all color libs from MZ but I can imagine we can replace `HSLuv` with `OKLCH` (or `okHSL`?) and we can feature-gate it like multiple other MZ parts. And then we can try to make it easier to integrate other libs. It would be a bit painful breaking change but that's the exact reason why I haven't released Zoon yet.

Regarding the default color palette: I'm not very satisfied with the current palette so there is a lot of room for improvements. I'm not sure if the right choice would be to define a better palette / gradients and allow devs to create sub-palettes from them or write helper functions/macros or generators, etc.
The goal is to start the development of MZ apps quickly and let the devs to refactor their ad hoc set of colors or styles in their app prototypes to proper "design systems" later (if needed at all). The API should just grow with your project, devs shouldn't need to do their own color research or hire designers just to start the project - MZ should guide them until it's no longer needed.

It's pretty difficult to design the API/behavior for it correctly - I can imagine it will take a while and there'll be many different point of views. Feel free to experiment and write your opinions (anybody), I'm open to changes but they should be aligned with general MZ philosophy described above.

**Comment by NeverGivinUp** [comment]
>  I can imagine we can replace `HSLuv` with `OKLCH` (or `okHSL`?)

I'm glad to hear that. For me `Okhsl` is the right choice, as it is based on the `Oklab` color space, but way easier to handle. I don't think developers will need much helper functions beyond the natural features of  `Okhsl`. Maybe not even a color crate like `palette`, because the hues are spread equidistantly. 

Regarding a color palette: Developers will need to make some design decisions. Imho frameworks should not have defaults, but instead make the need for decisions very visible. Providing an app for testing style choices visually over a variety of widgets is one possibility for visualizing the consequences of design choices. Examples should showcase the variety of possible designs (but that is a huge amount of work, so I wouldn't prioritize it).

For a rather striking (imo) example of the advantages of the perceived hue-linearity of the `Oklab` color space, see https://raphlinus.github.io/color/2021/01/18/oklab-critique.html. Set the quantization to 4 to 6 shades and look at the colors. When reds and greens are involved, it behaves just like `CIELab` (the basis of `HSLuv`) -- worse than `ICtCp` but much better than `sRGB`. But when blues are involved, `CIELab` (and thus `HSLuv`) is even worse than `sRGB`.

**Comment by MartinKavik** [comment]
UPDATE: I plan to wait until @NeverGivinUp's PR https://github.com/Ogeon/palette/pull/282 to `palette` is merged and the new `palette` version is released. Then we can try to integrate `pallete` into MZ and add some examples of writing color-related macros useful for writing MZ apps. Examples with `okhsl` and converting from hex would be nice.

**Comment by NeverGivinUp** [comment]
It's merged, cleaned up and published :)

**Comment by MartinKavik** [comment]
UPDATES:
1. There is a new palette based on OKLCH called Harmony:
    - https://www.producthunt.com/posts/harmony-accessible-ui-color-palette
    - https://twitter.com/romanshamin_en/status/1707756732674416806
    - https://www.figma.com/community/file/1287828769207775946
    - https://github.com/evilmartians/harmony
   
    I can imagine it could resolve the issue with the default MZ color palette.

2. Just a reference to the `pallete` issue mentioned in the previous comment:
    - https://github.com/Ogeon/palette/issues/296

3. During this MoonZoon development iteration I was focusing mostly on the frontend architecture and frontend multithreading but I would like to focus on colors (this issue) during the next iteration.

**Comment by NeverGivinUp** [comment]
The Harmony palette uses oklch colors in the browsers. And its algorithm seems to match browser colors, but not @bottosson's reference computations

For example (this is not a color from the Harmony palette) oklch(40%, 0.11, 240) is a blue on the edge of SRGB space. [Ottosson](https://bottosson.github.io/misc/colorpicker/#006596) computes it to RGB #006495 (give or take, there are rounding errors). [Evil Martians' converter ](https://oklch.com/#40,0.11,240,100) computes it to RGB #004d74, which is outside SRGB space (shown in the graphs of the converter). It changes RGB #006495 to ##016495 (which is fine) and computes it to oklch(48% 0.11 240.16), which is way lighter. Optically however oklch(48% 0.11 240.16) in the browser produces the color that Ottosson's implementation produces for  oklch(40%, 0.11, 240). Either Ottosson's own site or the browsers (I tried Edge and Firefox) are wrong.
